version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: festivaldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: festivaldb
    ports:
      - "3307:3306"  # Expose MySQL on localhost:3307
    volumes:
      - db_data:/var/lib/mysql  # Persistent MySQL data
      - ./Database/festival.sql:/docker-entrypoint-initdb.d/festival.sql  # Initialize DB
    command: --default-authentication-plugin=mysql_native_password
    restart: always  # Restart on failure

  web:
    env_file:
      - .env
    build:
      context: ./FritFest.API  # Path to your .NET Core API project
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=festivaldb;User=root;Password=${DB_PASSWORD};
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"  
    depends_on:
      - db  # Ensure the database service starts first
    restart: always  # Restart on failure

volumes:
  db_data:  # Named volume for persistent MySQL storage
